"""Initial migration

Revision ID: 740e18e317b4
Revises: 
Create Date: 2025-02-20 19:32:13.215141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740e18e317b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_well_number', sa.String(length=20), nullable=False),
    sa.Column('oil', sa.Integer(), nullable=True),
    sa.Column('gas', sa.Integer(), nullable=True),
    sa.Column('brine', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_well_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annual_production')
    # ### end Alembic commands ###
